---
abstract: 'Load your commonly-used modules in a single import'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::More: '0'
  lib: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ToolSet
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  ToolSet:
    file: lib/ToolSet.pm
    version: '1.01'
  ToolSet::SWC:
    file: lib/ToolSet/SWC.pm
    version: '1.01'
requires:
  Carp: '0'
  base: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/ToolSet/issues
  homepage: https://github.com/dagolden/ToolSet
  repository: https://github.com/dagolden/ToolSet.git
version: '1.01'
x_authority: cpan:DAGOLDEN
